name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.https://gist.github.com/Jaemm/f02a2e6f131b2e69d94d743a098ad181 }}
          TIMEZONE: Asia/Seoul
